language: python
os: linux
dist: xenial

python:
  - 3.9
  
install:
  - pip install -q -r requirements-dev.txt codecov

script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro

after_success:
  - codecov